### ISSUE TITLE
Example of /etc/gitlab-runner/config.toml

### ISSUE THREAD

**Issue by ghost** [eyeson-team/pogo#1]
Hello and thank you for this repository!

I am trying to set up the executor on Ubuntu 20.04 but it does not seem to work. The run_exec section of my config.toml is empty

```
[[runners]]
  name = "Podman"
  url = "http://1.2.3.4"
  token = "mmmmmmmmmmmmmmm"
  executor = "custom"
  builds_dir = "/builds"
  cache_dir = "/cache"
  shell = "bash"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.custom]
    config_exec = "/root/bin/pogo"
    config_args = ["config", "--config", "/root/.pogo.yaml"]
    run_exec = ""
```

Could you post an example of how the config.toml file should look like?

Best regards

**Comment by unused** [comment]
Hi there, the commands for each step need to be configured. This is a bit much to write - or copy and paste - that's why there is a [register task in the Makefile](https://github.com/eyeson-team/pogo/blob/main/Makefile#L45). For sure you can also just edit your config.toml afterwards. There's an example below. Additionally from your config I read that you're using user root to host your gitlab runner, I strongly recommend to use a regular user instead. That is imho the major advantage of podman over the docker gitlab executor as well.

```
concurrent = 5
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "pogo-runner"
  url = "https://gitlab.com"
  token = "******"
  executor = "custom"
  builds_dir = "/builds"
  cache_dir = "/cache"
  shell = "bash"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.custom]
    config_exec = "/home/runner/bin/pogo"
    config_args = ["config", "--config", "/home/runner/.pogo.yaml"]
    prepare_exec = "/home/runner/bin/pogo"
    prepare_args = ["prepare", "--config", "/home/runner/.pogo.yaml"]
    run_exec = "/home/runner/bin/pogo"
    run_args = ["run", "--config", "/home/runner/.pogo.yaml"]
    cleanup_exec = "/home/runner/bin/pogo"
    cleanup_args = ["clean", "--config", "/home/runner/.pogo.yaml"]
```
